/*
 * dicestrings.inc
 *
 *  Created: 2022-11-29 17:21:22
 *   Author: Ibrahim Akiel och Ömer Kolsuz
 */ 

 
;==============================================================================
; Definition of strings
;==============================================================================
 	Str_1:		.DB "Welcome Magnus  !",0			
	Hello_str1: .DB "Hello",0
	Dice_start: .DB "Welcome Magnus!    ",0
	Dice_roll:	.DB "Magnus is Rolling!  ",0,0
 	Dice_2:		.DB "Magnus press 2 ",0
	Dice_value: .DB "Value: ",0
	Dice_temp: .DB	"Stats:",0,0
	Dice_temp1: .DB	"Clear",0
	Dice_temp2: .DB	"Monitor",0

	
